Falsehoods typo - prefix should be suffix
google/libphonenumber pull request #2729
Opened 2022-02-12 16:43 UTC by nicrodgers

This particular falsehood talks about dialling more digits _after_ a number and so should be described as a suffix rather than prefix.

2022-02-16 12:50 UTC, netgsm commented
Hi ,
There is now a new MVNO in Turkey. Can you add prefix 9051022 Netgsm Mobile

2022-02-17 00:41 UTC, Nourhazimhmaidi approved these changes

2022-02-17 00:44 UTC, Nourhazimhmaidi approved these changes

2022-02-21 16:34 UTC, lararennie requested changes
Actually, the original was correct. The idea is basically that people assume since "999" is a number, that "999111" can't be, since you've already connected to 999 and the subsequent digits are just dropped/ignored. This is used for toll-free numbers in e.g. the US where it's 1800 LONGWORD and you could have dialled 1800 LONGWOR and it works too.

However, in a few countries, like Brazil, this does not hold, and you have to dial the exact numbers.

Perhaps we need to make the explanation more understandable?

2022-07-11 08:47 UTC, closed without merging