appengine-api-1.0-sdk --> appengine-maven-plugin
google/libphonenumber pull request #2833
Opened 2022-10-12 10:13 UTC by roggnroll

2022-10-19 08:22 UTC, tvislavski requested changes

2022-10-19 08:22 UTC, tvislavski commented on java/demo/README.md
> +![App Engine Run Config](/Users/rogg/IdeaProjects/libphonenumber/java/demo/.readme_res/App_Engine_Run_Config.png)
This shouldn't be your local path :)

2022-10-19 11:55 UTC, roggnroll commented on java/demo/README.md
> +![App Engine Run Config](/Users/rogg/IdeaProjects/libphonenumber/java/demo/.readme_res/App_Engine_Run_Config.png)
ah, good catch, thanks!

2022-10-20 09:11 UTC, tvislavski approved these changes

2022-10-20 10:55 UTC, merged